import React from 'react';
import { QueryStatus } from '../hooks/useRagQuery';
import { renderTextWithCitations } from '../lib/markdown';

/**
 * Props for the AnswerPanel component.
 */
export interface AnswerPanelProps {
  /** Current status of the RAG pipeline */
  status: QueryStatus;
  /** Streamed text answer generated by the LLM */
  answer: string | null;
  /** Error message to show if any phase in the pipeline fails */
  error: string | null;
  /** Highlighted citation index hovered in the source card list */
  highlightedIndex: number | null;
  /** Callback to set or clear the highlighted citation index */
  setHighlightedIndex: (idx: number | null) => void;
  /** Transformed / expanded search query (optional) */
  transformedQuery?: string | null;
}

/**
 * AnswerPanel component displays the streaming answer markdown text along with its
 * citation tags, current generation status (searching, reranking, generating),
 * loading shimmers, and error notices.
 * 
 * @param {AnswerPanelProps} props The props for the component.
 * @returns {React.ReactElement} The rendered answer panel.
 */
export const AnswerPanel: React.FC<AnswerPanelProps> = ({
  status,
  answer,
  error,
  highlightedIndex,
  setHighlightedIndex,
  transformedQuery,
}) => {
  const isGeneratingActive = status !== 'completed' && status !== 'error' && status !== 'idle';

  return (
    <div className="glass-panel answer-panel" style={{ display: 'flex', flexDirection: 'column' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '1px solid rgba(255, 255, 255, 0.06)', paddingBottom: '12px' }}>
        <h2 style={{ fontSize: '1.25rem', fontWeight: 600, color: 'var(--text-primary)' }}>Generative Answer</h2>
        {isGeneratingActive && (
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
            <span className="status-dot active" />
            <span>
              {status === 'routing'
                ? 'Routing Intent...'
                : status === 'expanding'
                ? 'Expanding Query...'
                : status === 'searching' 
                ? 'Web Searching...' 
                : status === 'reranking' 
                ? 'Cohere Reranking...' 
                : 'Generating...'}
            </span>
          </div>
        )}
      </div>

      {error && (
        <div 
          style={{ 
            padding: '16px', 
            borderRadius: '8px', 
            background: 'rgba(239, 68, 68, 0.08)', 
            border: '1px solid rgba(239, 68, 68, 0.2)', 
            color: 'var(--accent-error)',
            fontSize: '0.9rem',
            marginBottom: '16px'
          }}
        >
          ❌ {error}
        </div>
      )}

      {/* Shimmer states for initial pipeline stages when no answer has arrived yet */}
      {(status === 'routing' || status === 'expanding' || status === 'searching' || status === 'reranking') && !answer && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', flex: 1 }}>
          <div className="shimmer-bg" style={{ height: '18px', width: '80%', borderRadius: '4px' }} />
          <div className="shimmer-bg" style={{ height: '18px', width: '95%', borderRadius: '4px' }} />
          <div className="shimmer-bg" style={{ height: '18px', width: '60%', borderRadius: '4px' }} />
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
            {status === 'routing'
              ? 'Analyzing query intent...'
              : status === 'expanding'
              ? 'Rewriting search query...'
              : status === 'searching' 
              ? (transformedQuery ? `Searching for "${transformedQuery}"...` : 'Fetching documents from Tavily...') 
              : 'Evaluating relevance with Cohere Rerank...'}
          </div>
        </div>
      )}

      {/* Streamed Answer Area */}
      {answer && (
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
          <div className="answer-markdown" style={{ flex: 1 }}>
            {renderTextWithCitations(answer, highlightedIndex, setHighlightedIndex)}
          </div>
          {status !== 'completed' && (
            <span 
              style={{ 
                display: 'inline-block', 
                width: '8px', 
                height: '14px', 
                background: 'var(--accent-primary)', 
                animation: 'pulse-glow 1s infinite', 
                marginLeft: '4px',
                verticalAlign: 'middle'
              }} 
            />
          )}
        </div>
      )}
    </div>
  );
};

export default AnswerPanel;
